<a href="https://colab.research.google.com/github/woodRock/deep-learning-goodfellow/blob/main/chapter_2_linear_algebra.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Chapter 2

# Scalers, Vectors, Matrices and Tensors

In [59]:
import numpy as np
import torch

# A scalar is just a single number
scalar = 1

# A vector in an array of numbers.
vector_numpy = np.array([1,2,3,4,5])
vector_torch = torch.tensor([1,2,4,5])

# A matrix in a 2-D array of numbers
matrix_numpy = np.array([[1,2,3],[4,5,6]])
matrix_torch = torch.tensor([[1,2,3],[4,5,6]])

# A_{i,;} denotes a horizontal cross section of a matrix.
print(f"matrix_numpy[0,:] : {matrix_numpy[0,:]}")
print(f"matrix_torch[0,:] : {matrix_torch[0,:]}")

# A_{:,i} denotes the ith column of the matrix.
print(f"matrix_numpy[:,0] : {matrix_numpy[:,0]}")
print(f"matrix_torch[:,0] : {matrix_torch[:,0]}")

# A tensor is an array with more than 2 axes.
tensor_numpy = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
tensor_torch = torch.tensor([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])

# The tranpose of a matrix is the mirror image of the matrix across a diagonal line.
print(f"matrix_numpy.T : {matrix_numpy.T}")
print(f"matrix_torch.T : {matrix_torch.T}")

# We denote the tranpose of a matrix A as A^T, and is defined such that (A^T)_{i,j} = A_{i,j}
print(f"matrix_numpy.T[0][1] == matrix_numpy[1][0]: {matrix_numpy.T[0][1] == matrix_numpy[1][0]}")

# The transpose operator can turn a row matrix into a standard column vector.
print(f" {np.array([[1,2,3]]).T}")

# A scalar can be thought of as a matrix with only a single entry, a scalar is its own transpose a^T = a
print(f"np.array(1).T == np.array(1) : {np.array(1).T == np.array([1])}")

# We allow the addition of a matrix and a vector
A = np.array([[1,2,3],[4,5,6]])
b = np.array([1,2,3])
print(f"A + b : {A + b}")
# The implicit copying for b to many locations is called broadcasting.

matrix_numpy[0,:] : [1 2 3]
matrix_torch[0,:] : tensor([1, 2, 3])
matrix_numpy[:,0] : [1 4]
matrix_torch[:,0] : tensor([1, 4])
matrix_numpy.T : [[1 4]
 [2 5]
 [3 6]]
matrix_torch.T : tensor([[1, 4],
        [2, 5],
        [3, 6]])
matrix_numpy.T[0][1] == matrix_numpy[1][0]: True
 [[1]
 [2]
 [3]]
np.array(1).T == np.array(1) : [ True]
A + b : [[2 4 6]
 [5 7 9]]


# Multiplying Matrices and Vectors

In [60]:
# Multiplying matrices and vectors
# A must have the same number of column as B has rows.
A = np.array([[1,2,3],[4,5,6]])
B = np.array([[1,2],[3,4],[5,6]])
print(f"A @ B : {A @ B}")

# The dot product between two vectors x and y of the same dimensionality is the matrix product x^Ty
x = np.array([1,2,3])
y = np.array([4,5,6])
print(f"np.dot(x,y) == x.T @ y : {np.dot(x,y) == x.T @ y}")

# Matrix prodduct operations have many useful properties.
A = np.array([[1,2,3],[4,5,6]])
B = np.array([[1,2],[3,4],[5,6]])
C = np.array([[1,2],[3,4],[5,6]])

# Matrix multiplication is distributive.
print(f"A @ (B + C) == A@B + A@C : {A @ (B + C) == A @ B + A @ C}")

A = np.array([[1,2,3],[4,5,6]])
B = np.array([[1,2],[3,4],[5,6]])
C = np.array([[1,2,3],[4,5,6]])

# Matrix multiplication is associative.
print(f"A @ (B @ C) == (A @ B) @ C : {A @ (B @ C) == (A @ B) @ C}")

A = np.array([[1,2,3],[4,5,6],[7,8,9]])
B = np.array([[9,8,7],[6,5,4],[3,2,1]])

# Matrix multiplication is not commutatuve. AB = BA dies not always hold.
print(f"A @ B == B @ A : {(A @ B == B @ A).all()}")

x = np.array([1,2,3])
y = np.array([4,5,6])

# The dot product between two vectors is commutative.
print(f"np.dot(x,y) == np.dot(y,x) : {np.dot(x,y) == np.dot(y,x)}")
print(f"(x.T @ y).T == x.T @ y : {(x.T @ y).T == x.T @ y}")
print(f"(x.T @ y).T == y.T @ x : {(x.T @ y).T == y.T @ x}")

A @ B : [[22 28]
 [49 64]]
np.dot(x,y) == x.T @ y : True
A @ (B + C) == A@B + A@C : [[ True  True]
 [ True  True]]
A @ (B @ C) == (A @ B) @ C : [[ True  True  True]
 [ True  True  True]]
A @ B == B @ A : False
np.dot(x,y) == np.dot(y,x) : True
(x.T @ y).T == x.T @ y : True
(x.T @ y).T == y.T @ x : True


# Identity and Inverse Matrices

$$
  A^{-1}A = I_n \\  
  Ax = b \\
  A^{-1}Ax = A^{-1}b \\
  I_n x = A^{-1}b \\
  x = A^{-1}b
$$

In [71]:
# An identidy matrix is a matrix that does not change any vector when we multiply that vector by that matrix.
print(f"Identity matrix - this is I_3: \n{np.eye(3)}")

I = np.eye(3)
A = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(f"A @ I == A: \n{A @ I == A}")

a = np.array([[1., 2.], [3., 4.]])
ainv = np.linalg.inv(a)
print(f"np.allclose(ainv @ a, np.eye(2)) : {np.allclose(ainv @ a, np.eye(2))}")

Identity matrix - this is I_3: 
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
A @ I == A: 
[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]
np.allclose(ainv @ a, np.eye(2)) : True
